# Exercise 2.B Cleaning up data

Start by importing numpy (as np) AND pandas (as pd) into the notebook.

In [1]:
import numpy as np
import pandas as pd

# Importing NumPy as np and pandas as pd. Pandas is the main tool I need because I’m working with table data, 
# and NumPy is also included because the exercise asks for it.

In a code cell, create a new DataFrame named df based on test_data.csv (as saved from the previous exercise).

In [2]:
df = pd.read_csv("test_data.csv")

df

# Using pd.read_csv() to bring the test_data.csv file into Python. I’m saving it as df, 
# which is now my original DataFrame. Then I display df to see the data before making any changes.

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

Add a cell to show column statistics on df using the describe method.

In [3]:
df.describe()

# Using describe() to get a quick summary of the numeric columns. This helps me understand the data better, 
# like the average, minimum, maximum, and how many values are in each column.

            ID       Age      Score
count  8.00000   6.00000   7.000000
mean   4.50000  25.00000  66.285714
std    2.44949   6.78233  32.576650
min    1.00000  18.00000  -1.000000
25%    2.75000  19.75000  60.000000
50%    4.50000  23.50000  78.000000
75%    6.25000  29.50000  87.500000
max    8.00000  35.00000  92.000000

## Filtering a DataFrame

Filter the DataFrame to show only rows where Age is greater than 18.

In [4]:
df[df["Age"] > 18]

# Focusing on the Age column and checking which ages are greater than 18. Then I pass that condition 
# back into the DataFrame so pandas only shows the rows where that condition is true.

   ID     Name   Age     City  Score
0   1   Alicia  25.0       NY   85.0
2   3  Charlie  22.0  Chicago   -1.0
3   4  Dominic  19.0  Houston   65.0
4   5      Eve  31.0  Phoenix   78.0
5   6    Frank  35.0   Boston    NaN

Filter the DataFrame to show only rows where Score is greater than 50 and less than 100.

In [5]:
df[(df["Score"] > 50) & (df["Score"] < 100)]

# Focusing on the Score column and checking two things at the same time. First, the score has to be greater than 50. 
# Second, the score has to be less than 100. The & means both conditions must be true.

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

## Modifying a DataFrame

Create new variable df_cleaned. Assign it the value of df, using the drop function to remove rows where the Score is less than 0 
(i.e., invalid score data). Then call df_cleaned to review the result.

In [6]:
df_cleaned = df.drop(df[df["Score"] < 0].index)

df_cleaned

# Focusing on the Score column and checking two things at the same time. First, the score has to 
# be greater than 50. Second, the score has to be less than 100. The & means both conditions must be true.
# I save the result as df_cleaned so my original df stays safe, and then I display df_cleaned to check that the invalid row was removed.

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

Continuing to work with df_cleaned for the rest of these steps, remove the City column from the DataFrame using drop. Call df_cleaned to review the result.

In [7]:
df_cleaned = df_cleaned.drop(columns=["City"])

df_cleaned

# I pass the City column into drop() and tell pandas I want to remove that column. 
# Then I save the updated table back into df_cleaned and display it to confirm that City is gone.

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob   NaN   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace   NaN   55.0
7   8    Heidi  18.0   90.0

Replace all missing Age values with the mean Age of the DataFrame using fillna. Call df_cleaned to review the result.

In [8]:
df_cleaned["Age"] = df_cleaned["Age"].fillna(df_cleaned["Age"].mean())

df_cleaned

# Focusing on the Age column because some ages are missing. First, I calculate the average age using .mean(). 
# Then I use fillna() to replace the missing Age values with that average. Finally, I save the updated Age column back into df_cleaned.

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

Replace any Score value of 0 with the mean Score of the DataFrame using replace. Call df_cleaned to review the result.

In [9]:
df_cleaned["Score"] = df_cleaned["Score"].replace(0, df_cleaned["Score"].mean())

df_cleaned

# Focusing on the Score column again. This time, I’m looking for scores that are exactly 0. Since the exercise treats 0 as 
# something that should be replaced, I calculate the average score and use that average to replace the 0 values.

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

Remove any remaining rows that contain NaN values using the dropna function. Call df_cleaned to review the result.

In [10]:
df_cleaned = df_cleaned.dropna()

df_cleaned

# Checking the whole DataFrame for any remaining missing values. If a row still has a NaN, that row gets removed.
# Then I save the cleaned version back into df_cleaned.

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

Apply the values from ID as index labels, then remove column ID. (Pay attention to the numbering!) Call df_cleaned to review the result.

In [11]:
df_cleaned = df_cleaned.set_index("ID")

df_cleaned

# Taking the ID column and making it the index, which means it becomes the row label on the left side
# instead of staying as a normal column. Then I display the final cleaned DataFrame.

       Name   Age  Score
ID
1    Alicia  25.0   85.0
2       Bob  25.6   92.0
4   Dominic  19.0   65.0
5       Eve  31.0   78.0
7     Grace  25.6   55.0
8     Heidi  18.0   90.0