# Exercise 2.C Working with multiple DataFrames

Start by importing numpy (as np) AND pandas (as pd) into the notebook.

In [1]:
import numpy as np
import pandas as pd

# Importing NumPy and giving it the nickname np.
# Importing pandas and giving it the nickname pd because I need pandas to create and work with DataFrames.

## Basic Aggregations

Create a DataFrame named df_sales

In [3]:
data = {
    "Product": ["A", "B", "C", "A", "B", "C", "A", "B", "C"],
    "Region": ["North", "South", "East", "West", "North", "South", "East", "West", "North"],
    "Units_Sold": [10, 15, 20, 5, 10, 15, 10, 5, 15],
    "Price": [100, 200, 150, 100, 200, 150, 100, 200, 150]
}

df_sales = pd.DataFrame(data)

df_sales

# Creating a dictionary called data. This is where the sales information gets stored before turning it into a DataFrame.
# Each list represents the values that will go inside that column.

  Product Region  Units_Sold  Price
0       A  North          10    100
1       B  South          15    200
2       C   East          20    150
3       A   West           5    100
4       B  North          10    200
5       C  South          15    150
6       A   East          10    100
7       B   West           5    200
8       C  North          15    150

Add a new column Revenue to df_sales by multiplying Units_Sold and Price.

In [4]:
df_sales["Revenue"] = df_sales["Units_Sold"] * df_sales["Price"]

df_sales

# Focusing on the Units_Sold and Price columns because revenue is calculated by multiplying those together.
# After the calculations, I save them into a brand-new column called Revenue. Then I display df_sales again 
# so I can confirm the new column was added correctly.

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

Use the sum function to calculate the total Units_Sold and total Revenue across all products and regions.

In [11]:
total_units_sold = df_sales["Units_Sold"].sum()
total_revenue = df_sales["Revenue"].sum()

print(f"Total Units Sold: {total_units_sold:,}")
print(f"Total Revenue: ${total_revenue:,.2f}")

# Focusing on the Units_Sold column to add every value together using .sum(). I save that total into a variable called 
# total_units_sold so I can use it later. Then I repeat the same process with the Revenue column by adding all revenue values together 
# and storing the result in total_revenue. Finally, I print both totals so I can clearly see the results.

Total Units Sold: 105
Total Revenue: $16,000.00

Use the mean function to calculate the average Units_Sold and average Revenue.

In [13]:
average_units_sold = df_sales["Units_Sold"].mean()
average_revenue = df_sales["Revenue"].mean()

print(f"Average Units Sold: {average_units_sold:,.2f}")
print(f"Average Revenue: ${average_revenue:,.2f}")

# Again focusing on the Units_Sold column, but now using .mean() to calculate the average.
# I save that answer into average_units_sold. Then I repeat the same process for the Revenue column to calculate
# the average revenue and save it in average_revenue. Finally, I print both answers so I can review the averages.

Average Units Sold: 11.67
Average Revenue: $1,777.78

## Grouping Data

Use the groupby function to group df_sales by Product and calculate the total Units_Sold and total Revenue for each product.

In [14]:
product_totals = df_sales.groupby("Product")[["Units_Sold", "Revenue"]].sum()

product_totals

# Grouping the sales using the product column and using sum() to calculate how many total units were sold using values in the Units_Sold column
# and again using sum() to calculate how much revenue each product made using the values in the Revenue column.

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

Use the groupby function to group df_sales by Region and calculate the average Units_Sold and average Revenue for each region.

In [15]:
region_averages = df_sales.groupby("Region")[["Units_Sold", "Revenue"]].mean()

region_averages

# This time, grouping by region. Focusing on Units_Sold and Revenue column and using mean() to calculate the average units sold
# and the average revenue for each region.

        Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

Use the groupby function to group df_sales by both Product and Region and calculate the sum of Units_Sold and Revenue for each combination.

In [16]:
product_region_totals = df_sales.groupby(["Product", "Region"])[["Units_Sold", "Revenue"]].sum()

product_region_totals

# Grouping the DataFrame by two columns: Product and Region. Organizing the rows by product and then within each product, also organizing it by region.
# Focusing again on Units_Sold and Revenue, I used sum() to total those values for each Product and Region combination.

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

Sort df_sales by Units_Sold in ascending order.

In [22]:
df_sales.sort_values(by="Units_Sold", ascending=True)

# Sorting the Units_Sold column using sort_values and specifying true for ascending, meaning it will show the lowest to the highest values.
# Since this is not saved into a variable, this will only show me a sorted version temporarily.

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

Sort df_sales by Revenue in descending order.

In [23]:
df_sales.sort_values(by="Revenue", ascending=False)

# Sorting the Revenue column and specifying false for ascending, meaning it will show the highest to the lowest values.

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
8       C  North          15    150     2250
5       C  South          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

Add a new column Revenue_Rank to df_sales, which ranks the Revenue values in descending order (i.e., highest revenue has rank 1).
Call df_sales to review the changes.

In [32]:
df_sales["Revenue_Rank"] = df_sales["Revenue"].rank(ascending=False, method="dense")

df_sales

# The .rank(ascending=False, method="dense") part is what creates the ranking in descending order. After Python creates the rankings, 
# I save them into a brand-new column called Revenue_Rank. Finally, I display df_sales again to make sure the new ranking column was added correctly.
# Without method="dense" decimals can happen because .rank() uses average ranking by default when values tie.

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000           4.0
1       B  South          15    200     3000           1.0
2       C   East          20    150     3000           1.0
3       A   West           5    100      500           5.0
4       B  North          10    200     2000           3.0
5       C  South          15    150     2250           2.0
6       A   East          10    100     1000           4.0
7       B   West           5    200     1000           4.0
8       C  North          15    150     2250           2.0

## Merging DataFrames

Create a new DataFrame named df_products.

In [33]:
product_data = {
    "Product": ["A", "B", "C"],
    "Category": ["Electronics", "Furniture", "Appliances"]
}

df_products = pd.DataFrame(product_data)

df_products

# creating a second dictionary called product_data to hold extra information about the products. 
# This time, I’m adding a Category column so each product has a category label.
# I pass it into pd.DataFrame() so pandas can turn it into a table. I save this second table into a variable called df_products. 
# Finally, I display it to make sure everything loaded correctly.

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

Merge df_sales with df_products on the Product column, resulting in a new DataFrame named df_merged.
Call df_merged to review the merged DataFrame.

In [35]:
df_merged = pd.merge(df_sales, df_products, on="Product")

df_merged

# Taking the sales table and products table and matching them using the Products column.
# Python will look at Product A, B, and C in both DataFrames and match the correct category to each sale.
# After the merge happens, I save the combined DataFrame into a new variable called df_merged.

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000           4.0  Electronics
1       B  South          15    200     3000           1.0    Furniture
2       C   East          20    150     3000           1.0   Appliances
3       A   West           5    100      500           5.0  Electronics
4       B  North          10    200     2000           3.0    Furniture
5       C  South          15    150     2250           2.0   Appliances
6       A   East          10    100     1000           4.0  Electronics
7       B   West           5    200     1000           4.0    Furniture
8       C  North          15    150     2250           2.0   Appliances

Use groupby on df_merged to calculate the total Revenue by Category.

In [37]:
category_revenue = df_merged.groupby("Category")["Revenue"].sum()

category_revenue

# Grouping the rows based on Category and then adding it all up based on revenue inside each category.
# The result will be saved in the category_revenue variable.

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64